# Generated by Django 5.2.5 on 2025-09-09 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Numer wózka')),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=430, max_digits=7, verbose_name='Pojemność [kg]')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Kod batona')),
                ('flavor', models.CharField(max_length=50, verbose_name='Smak')),
                ('tank', models.CharField(max_length=50, verbose_name='Tank')),
                ('pieces', models.PositiveIntegerField(default=66, verbose_name='Sztuk na wózku')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Masa [kg]')),
                ('produced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Czas wyprodukowania')),
                ('status', models.CharField(choices=[('IN_COLD_ROOM', 'W magazynku'), ('TAKEN_TO_PRODUCTION', 'Zdjęty do produkcji')], default='IN_COLD_ROOM', max_length=32)),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Czas zdjęcia')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='core.cart')),
            ],
            options={
                'ordering': ['-produced_at'],
            },
        ),
    ]
