# Generated by Django 5.2.5 on 2025-09-09 19:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='packing_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data pakowania'),
        ),
        migrations.AddField(
            model_name='load',
            name='product_kind',
            field=models.CharField(choices=[('Naturalny', 'Naturalny'), ('Ziołowy', 'Ziołowy'), ('Pomidorowy', 'Pomidorowy')], default='Naturalny', max_length=20, verbose_name='Rodzaj batonu'),
        ),
        migrations.AddField(
            model_name='load',
            name='production_shift',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=4, verbose_name='Zmiana'),
        ),
        migrations.AlterField(
            model_name='load',
            name='flavor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Smak'),
        ),
        migrations.AlterField(
            model_name='load',
            name='product_code',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Kod batonu (1–365)'),
        ),
        migrations.AlterField(
            model_name='load',
            name='tank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tank'),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Masa [kg]'),
        ),
    ]
