# Generated by Django 5.2.5 on 2025-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_packing_date_load_product_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='handled_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prowadził'),
        ),
    ]
