# Generated by Django 5.2.5 on 2025-09-09 21:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_load_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='handled_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wprowadził'),
        ),
        migrations.AlterField(
            model_name='load',
            name='pieces',
            field=models.PositiveIntegerField(default=66, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(66)], verbose_name='Sztuk na wózku'),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa [kg]'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status'], name='core_load_status_6b6eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['produced_at'], name='core_load_produce_764fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['cart', 'status'], name='core_load_cart_id_b97428_idx'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_COLD_ROOM')), fields=('cart',), name='unique_active_load_per_cart'),
        ),
    ]
