# Generated by Django 5.2.5 on 2025-09-09 21:58

import core.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_load_handled_by_alter_load_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='product_code',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=1, help_text='Podaj masę w kilogramach w skokach co 0,5 kg (np. 123.0, 123.5).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), message='Masa nie może być ujemna.'), django.core.validators.MaxValueValidator(Decimal('500.0'), message='Masa wózka nie może przekraczać 500 kg.'), core.models.validate_half_kg], verbose_name='Masa [kg]'),
        ),
    ]
