# Generated by Django 5.2.5 on 2025-09-10 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_load_product_code_alter_load_total_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=16)),
                ('ref_id', models.IntegerField(db_index=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='load',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='load',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Wewnętrzna wersja rekordu do CAS.'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status', 'produced_at'], name='core_load_status_b0c389_idx'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.CheckConstraint(condition=models.Q(('pieces__gte', 1), ('pieces__lte', 66)), name='pieces_in_1_66'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.CheckConstraint(condition=models.Q(('product_code__gte', 1), ('product_code__lte', 365)), name='product_code_1_365'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['model', 'action'], name='core_eventl_model_f667c9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['ts'], name='core_eventl_ts_bab795_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['ref_id'], name='core_eventl_ref_id_871f2c_idx'),
        ),
    ]
