# Generated by Django 5.2.5 on 2025-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas edycji'),
        ),
        migrations.AddField(
            model_name='load',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edytował'),
        ),
    ]
