# Generated by Django 5.2.5 on 2025-09-10 20:37

import core.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_load_edited_at_load_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='initial_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('500.0')), core.models.validate_half_kg], verbose_name='Masa początkowa [kg]'),
        ),
    ]
