# Generated by Django 5.2.5 on 2025-09-21 11:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='load',
            name='product_kind',
            field=models.CharField(choices=[('Naturalny', 'Naturalny'), ('Ziołowy', 'Ziołowy'), ('Pomidorowy', 'Pomidorowy')], default='Naturalny', max_length=20, verbose_name='Rodzaj batona'),
        ),
        migrations.CreateModel(
            name='TunnelRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(max_length=20)),
                ('product_code', models.PositiveIntegerField()),
                ('bar_production_date', models.DateField(blank=True, null=True)),
                ('cooling_time_min', models.IntegerField(blank=True, null=True)),
                ('temp_tunnel', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_inlet', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_shell_out', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_core_out', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('taken_carts_csv', models.CharField(blank=True, default='', max_length=512)),
                ('sum_taken_kg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('order_no', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.tunnelday')),
            ],
            options={
                'ordering': ['order_no', 'id'],
                'indexes': [models.Index(fields=['day', 'order_no'], name='core_tunnel_day_id_07b7d8_idx'), models.Index(fields=['product_kind'], name='core_tunnel_product_608a58_idx'), models.Index(fields=['product_code'], name='core_tunnel_product_c03c4c_idx')],
            },
        ),
    ]
