# Generated by Django 5.2.5 on 2025-09-21 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tunnelday_alter_load_product_kind_tunnelrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelrow',
            name='cooling_time_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='tunnelrow',
            name='product_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='tunnelrow',
            name='product_kind',
            field=models.CharField(choices=[('Naturalny', 'Naturalny'), ('Ziołowy', 'Ziołowy'), ('Pomidorowy', 'Pomidorowy')], max_length=20),
        ),
    ]
