# Generated by Django 5.2.5 on 2025-09-21 19:18

import core.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tunnelrow_cooling_time_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='cart_weight_snapshot',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, help_text='Wartość ustawiana automatycznie przy zdejmowaniu do produkcji.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('500.0')), core.models.validate_half_kg], verbose_name='Masa w momencie zdjęcia [kg]'),
        ),
    ]
