# Generated by Django 5.2.5 on 2025-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_load_cart_weight_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='default', max_length=32, unique=True)),
                ('days_count', models.PositiveSmallIntegerField(default=1)),
                ('dates', models.JSONField(default=dict)),
                ('pcs', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'production_plan',
            },
        ),
    ]
